### ISSUE TITLE
Invalid RTC Capture File, tried with various versions

### ISSUE THREAD

**Issue by yan-map** [eliemichel/MapsModelsImporter#104]
I have tried before (on August) and everything worked perfevtly, but now it's always an error on import in blender "Invalid RTC Capture File"

I have tried more old rdc's, but doesn't work for me now

 - The .rdc file [link](https://drive.google.com/file/d/1vTMTcbvTr6pC9-3hghEgKcoBuVva3_S1/view?usp=sharing)
 - Your GPU name **Nvidia GeForce gtx 760**
 - Version of this add-on (must be the most recent one) **v0.3.3-rc1, tested 0.3.2 and 0.3.1 - doesn't work**
 - Version of RenderDoc (1.9 recommended, do not use v1.10) **v1.10 (1.9,1.7 tested - doesnt work)**
 - Version of Blender (2.82 minimum) **2.91, 2.83 tested - doesn't work**

_Invalid RDC capture file. Please make sure that:
1. You are importing from Google Maps (NOT Google Earth)
2. You were MOVING in the 3D view while taking the capture (you can use the Capture after delay button in RenderDoc).
Please report to MapsModelsImporter developers providing the .rdc file as well as the full console log.
Console log is accessible in Windows > Toggle System Console (right click to copy)._

**Comment by mnick86** [comment]
Same on my side. Also attached rdc file:
https://easyupload.io/gt2kjt

**Comment by eliemichel** [comment]
@yan-map For some reason your capture is missing texture images on my side. Can you see textures in renderdoc on your side?

![image](https://user-images.githubusercontent.com/5802849/97078483-d3836180-15ec-11eb-9667-60e8070f7797.png)

You may try this slight update that handles missing imgaes: https://github.com/eliemichel/MapsModelsImporter/releases/tag/v0.3.3 But the capture seems to have another problem, regarding bloc positions, let me know.

@mnick86 No problem on my side with yours:
![image](https://user-images.githubusercontent.com/5802849/97078193-a03fd300-15ea-11eb-914f-47dec249e058.png)

Could you give details by enabling debug log in the add-on's preferences and copying here (as text, not as screenshot) the content of the Window > System Console? (Also prefer openning new issues of your own in the future rather than mixing with potentially unrelated ones ;) )

**Comment by mnick86** [comment]
worked with the latest version, thanks!
