### ISSUE TITLE
Chrome unsupported command-line flag

### ISSUE THREAD

**Issue by JarekB** [eliemichel/MapsModelsImporter#11]
Just came across your add-on - looks brilliant, thanks : ) Unfortunately after installing all software needed and spending lots of time trying to make it work, no luck.
When running Chrome, I get a message at the top of the browser:
"You are using unsupported command-line flag: --disable-gpu-sandbox. Stability and security will suffer."
I guess it may be the reason why the injection doesn't work. I follow all the steps but the API: none is always shown, can't connect to the Chrome gpu process. 
Do you have any suggestions what to try ?

**Comment by eliemichel** [comment]
Actually, I also get this error message (you can see it in the video, though in French), but the flag actually  has an effect for me. Without it, the dialog box repops all the time and I cannot attach. With the `--disable-gpu-sandbox` flag, it's ok.
The last person who reported a similar issue succeeded using Vivaldi instead of Chrome. Some other used an older version of Chromium, like Chromium 61.0 or sth like this. Also, what GPU do you have?

**Comment by rickrichi** [comment]
I don't have NVidia or a GPU Card on my PC. Is this why I'm getting this error message?
I'm using Windows 10.

**Comment by eliemichel** [comment]
As I said above, everybody is having this message, it is a warning but not a string error. If you are having troubles using the add-on, check out the [https://github.com/eliemichel/MapsModelsImporter#troubleshooting](troubleshooting) section.
