### ISSUE TITLE
600mb rdc file 6gb GPU memory - GPU not enough memory

### ISSUE THREAD

**Issue by InterActivePlanning** [eliemichel/MapsModelsImporter#111]
Good day

I've tried to import and modify a 600mb rdc file with Blender. After hours, I can import it successfully, but moving the camera has a minute delay and I cannot export the file or do anything with it without getting a "not enough gpu memory" error. I have a 6gb gpu RTX 2060 (& 4 core/8 thread 4ghz cpu & 8gb ram & ssd)

I've also heard from others that exporting the file can make it three times bigger.

A computer without a graphics card and only 4gb ram can load the 600mb schene on the browser and function fine, but Blender on a pc with a graphics card and more ram can't handle it.

Not sure if Blender or file conversion can be optimized without noticeable quality loss to solve this issue, but if it can, it will be GREATLY appreciated. 

Ideally, I would like to import 6 x 600mb files into one scene for my architectural visualizations, but at the moment this is not possible.

**Comment by eliemichel** [comment]
Engineers at Google Maps made a good job at using hardware accelerated texture compression schemes, while this add-on uses standard PNG files for a more convenient manipulation in third party software. Blender is not a real time renderer, it is a content editing tool and a lot of optimizations that can be performed when knowing that a scene cannot change (which is the case in Google Maps) cannot work if there is a possibility at any time that the user may alter the content.

I'd suggest the following workflow:

 1. Split up data into manageable chunks. As soon as your 600Mb capture has been imported, move say quarters of it in individual collections (M key to move among collections). Deactivate all collections but one. If it is not enough, split into different blend files to ensure no unused data gets loaded. Build chunks according to level of interest so that you can downscale some of them more than the others.

 2. For each chunk, use [LilyTexturePacker](https://gumroad.com/l/DFExj), save the created "LilyTexturePacker" texture right away into a file because Blender sometimes "forgets" unsaved textures if you are at the limit of available RAM, apply the same material to all objects of the chunk (Ctrl+L > Material), maybe join them with Ctrl+J to be able to remove double points (M key in edit mode > By Distance).

 3. Purge the file (or close/reopen) for Blender to forget about tha now unused little textures, only the large packed texture is required.

 3. Downscale the packed texture (by a multiple of 2 to avoid pixel bleeding from one object to another). Individual chunks may have different downscaling factor depending on the area of interest.

 4. Now you may load into the same scene all of your chunks.

**Comment by InterActivePlanning** [comment]
Thank you very much.

I will give it a try.

Regards
Josiah Mos
