### ISSUE TITLE
cannot import RDC file- error message

### ISSUE THREAD

**Issue by mileseggy** [eliemichel/MapsModelsImporter#142]
When importing my rdc file i get this error message
![image](https://user-images.githubusercontent.com/78159867/106157828-048aa980-617b-11eb-96a5-14f1608e339f.png)
I also got the same error when using a sample file from this link
https://github.com/eliemichel/MapsModelsImporter-samples/blob/master/samples/alhambra-RD_1.11.rdc

I dont know much about coding, but importing this file would be very beneficial to a blender project of mine.
Thanks for any help you can provide
 
 GTX 1050ti
 Renderdoc 1.10
Blender 2.91, but I've tried using 2.82

**Comment by mileseggy** [comment]
please can someone help:)

**Comment by jokumo** [comment]
The sample file you linked does not work since it's RenderDoc 1.11. This is explained in the description at [https://github.com/eliemichel/MapsModelsImporter-samples](https://github.com/eliemichel/MapsModelsImporter-samples)

However, there should be a propper error Message. Your console output shows an unexpected crash that is not cached by the addon. 

Could you copy&paste the whole console output (starting from the first "Python: Traceback...") into a text file and upload it here? You can replace your username or delete it...
