### ISSUE TITLE
Cannot import RDC file

### ISSUE THREAD

**Issue by upyopyo** [eliemichel/MapsModelsImporter#143]
I cannot import my RDC files to blenders at all, but sample file 'funkhaus' is worked. Thus I am posting what's problems with my process.  And so far I tried:
- use a googlemap with chrome.
- I did moving in the 3d view, by panning, and rotate with "trigger after delay 5sec"

 - The .rdc file
 I made a zip file link because Github cannot attach files bigger than 10MB.
 https://drive.google.com/file/d/18DZydhoHwSW9qLpPzuomAjpnNHVlCnK3/view?usp=sharing

 - Your GPU name
 NVIDIA GeForce GTX 760
 
 - Version of this add-on (must be the most recent one)
 MapsModelsImporter-v0.3.4 and v0.3.5 (I tried the both).
 
 - Version of RenderDoc (1.10 recommended)
 v1.12
 - Version of Blender (2.82 minimum)
v2.91.2

Thanks!

![capture](https://user-images.githubusercontent.com/78295605/106378436-a36cfc80-6359-11eb-9302-3a908fb20660.JPG)

**Comment by jokumo** [comment]
RenderDoc Version 1.11 & 1.12 do not work for now (current MapsModelsImporter version is 0.3.5)

Anyway, try using sample rdc-files from here: [https://github.com/eliemichel/MapsModelsImporter-samples](https://github.com/eliemichel/MapsModelsImporter-samples)
That way you can figgure out if your problem is about MapsModelsImporter or if it's about your capture file.

Right now I don't have the time to test your rdc-file, but the screenshot looks like it something went wrong. The numbers in the brackets after "Draw" should be way bigger.

**Comment by upyopyo** [comment]
Thanks for your reply. 

yeah, as I said, the sample file 'funkhaus' is worked. 

it's good to know that 1.11 and 1.12 do not work, so I will try another Blender version.

**Comment by jokumo** [comment]
I suggest to try it first with your current installation of Blender and the sample files mentioned above. Most probably it's not about the Blender version.
1.11 and 1.12 refers to the RenderDoc version...

**Comment by polygonfuture** [comment]
Is 1.10 render doc version  newer or older from 1.5?   Naming conventions on renderdoc seem backward.   (I would assume 1.5 is newer version than 1.10 )

**Comment by upyopyo** [comment]
now it's working thanks!! I just clarify the versions I am using:
RenderDoc_1.10_64.msi
Blender 2.91.2
MapsModelsImporter-v0.3.4.zip (or MapsModelsImporter-v0.3.5-rc2.zip)

**Comment by jokumo** [comment]
> Just came here to say RenderDoc's naming convention seems flawed. They really should use zero padding to ensure versioning makes sense. 1.5 is a higher number than 1.10.

Not sure how you got to this conclusion. But looking at [RenderDoc's release page](https://github.com/baldurk/renderdoc/releases) I can't confirm your observation.

**Comment by eliemichel** [comment]
I believe they meant that version numbers should be 1.05 and 1.10 rather than respectively 1.5 and 1.10, in order to preserve the lexicographcial ordering of version numbers when represented as string. But imho representing version numbers as string is bad practice, they must be thought more as tuples, in which case 1.5 < 1.10. @polygonfuture a very commonly used versioning numbering is the so called *semantic versionning* -- which I believe RenderDoc follows -- and its specification clearly specifies that precedence is read as a tuple in [article 11](https://semver.org/#spec-item-11).
