### ISSUE TITLE
update on renderdoc

### ISSUE THREAD

**Issue by danai-c** [eliemichel/MapsModelsImporter#209]
Hey there, I used the suggested method previously and it worked just perfect. I've just encountered a new issue, since updating renderDoc. In the "file tab" it doesn't give me the option to "inject into process", anymore so not sure how to capture the desired bit from google maps. Do you know the solution around that? :}

**Comment by MisterCommand** [comment]
Hello, I have encountered the same issue. It seems like RenderDoc disabled this feature, please use RenderDoc v.1.13 for the latest release.

**Comment by adrgru** [comment]
The [release notes](https://github.com/baldurk/renderdoc/releases/tag/v1.14) include this:
"UI: Process injection is no longer available by default, as too many new users were getting confused and using it instead of launching their process through RenderDoc, which often broke. Since it is almost never the right method, it is now disabled by default and can be enabled in the settings the same way as global hooking."

This checkbox is found through "Tools" → "Settings" → "Enable process injection (restart required)".
