### ISSUE TITLE
Error importing RDC file in Blender

### ISSUE THREAD

**Issue by r3da11** [eliemichel/MapsModelsImporter#212]
Hello, I can't import any of the RDC files no matter how carefully I follow the videos or the suggestions in this issues page.

@eliemichel

![git](https://user-images.githubusercontent.com/102489181/160302420-9ea4d219-759c-4ce4-9459-622524f0653b.png)
============ &
![git2](https://user-images.githubusercontent.com/102489181/160302436-375dcaaa-f5ff-4132-99aa-b55f98f7f44c.png)

**Comment by UlrichE** [comment]
Hi,

same here. To be sure, that I have a valid rdc-file, I tried to import one of your Samples (MapsModelsImporter samples, Funkhaus.rdc).

renderdoc is version 1.18
blender is 3.1.0

Debug output says something about a wrong python version:
###
google_maps_rd failed and returned:
Error: Failed to load the RenderDoc Module. It however seems to exist.
This might be due to one of the following reasons:
 - Your Blender version uses another version of python than used to build the RenderDoc Module
 - An additional file required by the RenderDoc Module is missing (i.E. renderdoc.dll)
 - Something completely different

Remember, you must use exactly the same version of python to load the RenderDoc Module as was used to build it.
Find more information about building the RenderDoc Module here: https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Compiling.md

sys.platform:  win32
Python version:  3.10.2 (main, Jan 27 2022, 08:34:43) [MSC v.1928 64 bit (AMD64)]
err.name:  renderdoc
err.path:  C:\Users\###\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\MapsModelsImporter\bin\win64\renderdoc.pyd
Error Message:  DLL load failed while importing renderdoc: Das angegebene Modul wurde nicht gefunden.
###


Regards

Uli

**Comment by Revel8804** [comment]
Same here on windows and Blender 3.1.
Tried renderdoc 1.10, 1.18, and 1.19

`google_maps_rd failed and returned:
Error: Failed to load the RenderDoc Module. It however seems to exist.
This might be due to one of the following reasons:
 - Your Blender version uses another version of python than used to build the RenderDoc Module
 - An additional file required by the RenderDoc Module is missing (i.E. renderdoc.dll)
 - Something completely different

Remember, you must use exactly the same version of python to load the RenderDoc Module as was used to build it.
Find more information about building the RenderDoc Module here: https://github.com/baldurk/renderdoc/blob/v1.x/docs/CONTRIBUTING/Compiling.md

sys.platform:  win32
Python version:  3.10.2 (main, Jan 27 2022, 08:34:43) [MSC v.1928 64 bit (AMD64)]
err.name:  renderdoc
err.path:  C:\Users\kenny\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\MapsModelsImporter\bin\win64\renderdoc.pyd
Error Message:  DLL load failed while importing renderdoc: The specified module could not be found.



Extra info:
 - python = C:\Program Files\Blender Foundation\Blender 3.1\3.1\python\bin\python.EXE
 - python_home = C:\Program Files\Blender Foundation\Blender 3.1\3.1\python`
