### ISSUE TITLE
It's now impossible to use Google Chrome with RenderDoc to inject into Google Maps/Earth.

### ISSUE THREAD

**Issue by Zyberetro** [eliemichel/MapsModelsImporter#276]
Google Chrome will now on the newest version block me from injecting into it when I access Google Maps/Earth by changing the PID address whenever you inject into it. An example of this would be me loading Maps after I've injected into Chrome, and then it changes the PID address, so I then inject into the new address, and then when I do that, it changes the PID again, this literally goes on forever, which tells me that this is deliberately in there to stop people from injecting into Chrome using RenderDoc. 

The nasty thing about this is that I initially had a workaround by deliberately using an outdated version of Google Chrome (Brave is my main browser now, so I'm willing to do stuff like this), but it forces an auto-update that I've tried every method described on the internet to avoid, and they all failed. I'm cool with using Microsoft Edge but I don't know how, since the modified shortcut refers to Google Chrome and not Edge.

**Comment by spooknik** [comment]
Can also confirm this issue on all browsers based on Chromium V111. 

I suggest just grabbing a portable install of Ungoogled Chrome V110 and putting that in a folder somewhere (note: use only for this tool, do not use for general browsing, because eventually it will out of date) . I am not sure when or if Renderdoc will fix this issue with V111. 

https://github.com/Hibbiki/chromium-win64/releases/tag/v110.0.5481.178-r1084008

**Comment by Zyberetro** [comment]
> Can also confirm this issue on all browsers based on Chromium V111.
> 
> I suggest just grabbing a portable install of Ungoogled Chrome V110 and putting that in a folder somewhere (note: use only for this tool, do not use for general browsing, because eventually it will out of date) . I am not sure when or if Renderdoc will fix this issue with V111.
> 
> https://github.com/Hibbiki/chromium-win64/releases/tag/v110.0.5481.178-r1084008

Thank you so much, this works for me.

**Comment by edward93** [comment]
I keep getting the same issue even with v105 chromium (PID keeps switching)! 😞

**Comment by edward93** [comment]
> I keep getting the same issue even with v105 chromium (PID keeps switching)! 😞

Oh nvm! everything is working now!

**Comment by edward93** [comment]
@zp-yang I simply downloaded any chromium (I downloaded the `zip` from [here](https://ungoogled-software.github.io/ungoogled-chromium-binaries/releases/windows/64bit/110.0.5481.78-1))  v110! Then used the instructions from the readme to run it (using the chromium instead of my installed browser)! Initially it wasn't working because I was running `cmd` commands on `powershell` terminal!

**Comment by zp-yang** [comment]
It was working for me 2 weeks ago but suddenly stopped working this week. Today I reinstalled both rendoc and chrome and somehow it worked.

**Comment by Dusty323** [comment]
> 

This is absolutely maddening! My GPU PID keeps changing despite running chromium v110. That link you provided doesn't have a readme attached as to how to run it. Would you be able to further elaborate please? Pulling my hair out right now lol.

**Comment by DennieBee** [comment]
Cannot get it to work. Tried it on two different desktops. Both Chrome Latest, Chromium V110, Ungoogled Chromium V110, combined with with RenderDoc 1.27. Windows 10 and Windows 11. Nothing seems to work. I'm open to suggestions. Thanks!

**Comment by creativewax** [comment]
Can't get this working either no matter what combo of versions I use, PID just changes constantly, anyone got a fix for this?

**Comment by eliemichel** [comment]
> combined with with RenderDoc 1.27

Use version 1.25, as release notes say.

> My GPU PID keeps changing

Make sure RenderDoc and Chrome run on the same GPU (typically when using a laptop with integrated+dedicated chips)

Closing this issue as these problem are already listed in the troubleshooting section of the readme.
