### ISSUE TITLE
RenderDoc disconnected from process

### ISSUE THREAD

**Issue by John5i4** [eliemichel/MapsModelsImporter#3]
I've already done it properly a couple of days ago, getting some nice results in Blender.
I tried again today and I get:
RDOC 001100: [04:22:50]    win32_process.cpp( 577) - Log     - Injecting renderdoc into process 14236
RDOC 001100: [04:22:56]   target_control.cpp( 560) - Log     - Got remote handshake: chrome [14236]
RDOC 001100: [04:23:00]    win32_network.cpp( 222) - Warning - recv: WSAECONNRESET: An existing connection was forcibly closed by the remote host.

This happens on both 1.1 and 1.2, using the portable builds.

Thank you in advance for any help.

**Comment by eliemichel** [comment]
Hi @John5i4 do you still have this issue? Didn't you change anything about the browser between working and not working cases? Maybe you are using a laptop with both real GPU and integrated GPU, and the second time you were running on the integrated chip (possibly because running on battery rather than with power cordon pluged)?
