### ISSUE TITLE
Wrong Units transform of google map 3D model imported in Blender

### ISSUE THREAD

**Issue by cuiguangheng** [eliemichel/MapsModelsImporter#309]
Guys, I found that the google map model imported to blender it transform to a wrong units, kilometer in google map but meter in blender . Can anyone help to fix that? 
![image](https://github.com/eliemichel/MapsModelsImporter/assets/34788169/3223b55b-a822-402e-a20a-bf277bf3d60f)

**Comment by eliemichel** [comment]
Units are a known limitation of this process, because the actual physical units are present nowhere in the data we extract from Google Maps, and I was unable to figure out the inconsistency across various captures.

One solution is to measure a known distance both in Blender (`distance_blender`) and on the map (`distance_physical`) then compute `scale = distance_physical / distance_blender` and finally scale the whole scene by `scale`. **Pro-tip** Once you start a scaling operation with the 'S' key, you can directly input an exact scaling value using the keyboard.
