### ISSUE TITLE
please can you update it so code works with Renderdoc 1.32

### ISSUE THREAD

**Issue by ghost** [eliemichel/MapsModelsImporter#316]
If you are having trouble importing a .rdc file with this add-on, please provide the following information:

 - The .rdc file
 - Your GPU name
 - Version of this add-on
 - Version of RenderDoc
 - Version of Blender

Before even reporting, make sure that you are using [the last version](https://github.com/eliemichel/MapsModelsImporter/releases/latest) of this add-on and that you stick to the version of Blender and RenderDoc indicated in the release notes of this last version!

**Comment by eliemichel** [comment]
Each time I upgrade the version of RenderDoc that the add-on is based on, it is a lot of work because I need to build a custom version of RenderDoc's python module that matches Blender's python version. So no, I will not follow every single update of RenderDoc (I just did it for RD1.31), sorry if this forces you to downgrade by 1 version your RD.

If you wish to help though you may follow [the instructions from the doc](https://github.com/eliemichel/MapsModelsImporter/blob/master/doc/Building%20RenderDoc%20module.md) and share the python module, I'll be happy to include it in a new release!
