### ISSUE TITLE
Additional Textures Overriding Actual View

### ISSUE THREAD

**Issue by Superfreak1000** [eliemichel/MapsModelsImporter#34]
Hello! I would like to start off by saying thank you for creating this! It has been extremely helpful. However I encountered a problem I hadn't seen before. The process works exactly as before with no problems (extracting 3D geometry from Google Maps) until I noticed extra texture files in the Inputs tab.

![Capture4](https://user-images.githubusercontent.com/61470272/75269763-09064f80-57bf-11ea-9183-f7d603cfd095.JPG)

 The Outputs still looked correct. I saved and opened the file in Blender, as usual, only to find all of the textures replaced by this 

![Capture](https://user-images.githubusercontent.com/61470272/75269810-220f0080-57bf-11ea-9ed8-87064ce33ba0.JPG)

I cannot remove these textures to show the real colors. I am including the .rdc file for you to see.
Is this an issue with RenderDocs? Or a deliberate act by Google?

Please help.

https://www.dropbox.com/s/jw223rgeosw70l8/PB5.rdc?dl=0

**Comment by eliemichel** [comment]
You are not using the last version of the add-on, this issue has been fixed already, it was due to a change from using OpenGLES to D3D11 backend when capturing (the change of chrome.exe shortcut command).

Can you let me know how you got you download link for this add-on? You are not the first to use this very outdated version lately, I suspect there is a wrong link somewhere I'd like to fix it, try and recall exactly how you got here please! :)
