### ISSUE TITLE
Detect Google Earth captures to clearly reject them

### ISSUE THREAD

**Issue by eliemichel** [eliemichel/MapsModelsImporter#41]
Many people try to use this add-on with captures from Google Earth, while as I tried to advertise it as much as possible it only works with **Google Maps**. The error is always something about mdata not being defined, but the message is quite convoluted so it'd be better to catch this error and display an easier to understand message.

**Comment by eliemichel** [comment]
Also detect when the capture contains no 3D data because the user did not move in the viewport while capturing.

**Comment by albrrt** [comment]
Hi @eliemichel sorry if this isn't the best place to ask this - I tried looking for an email address but could't find any. 

I was wondering : I know this doesn't work with Google Earth but is there a plan or would it be possible to make this work with Google Earth in the future? The reason I ask is because the photogrammetry of Google Earth is better quality than Google Maps (Google Earth seems to devliver higher-resolution 3D models than Google Maps).

Thanks for your insights

**Comment by eliemichel** [comment]
I almost never use Google Earth so I naively though it was using the very same data. TBH I don't really understand why Maps and Earth are different products, but now that you said this I had a look. I think it uses the same data but indeed loads high resolution meshes on a wider area in Earth, so I'll consider it.

There is no technical limitation, it's more that it's taking time to analyse frames and automate data extraction, and I was thinking I did it once for Maps it's enough. Actually one of the reasons it fails at the moment is because uniforms have different names in Earth, but I think there are also differences in draw calls, the scrapping, should be modified a bit.

You can open an issue to request for this feature here on GitHub, it'll remind me - or anybody that want to help - to have a look at it!
