### ISSUE TITLE
Is it possible to use this "MapsModelsImporter" for games models or only google maps?

### ISSUE THREAD

**Issue by AccountZeroName** [eliemichel/MapsModelsImporter#47]
Is it possible to use this "MapsModelsImporter" for games models or only google maps?

I have this error in the blender log:

```
Traceback (most recent call last):
  File "C:\Users\andre\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\MapsModelsImporter\operators.py", line 53, in execute
    try:
  File "C:\Users\andre\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\MapsModelsImporter\google_maps.py", line 210, in importCapture
    if refMatrix:
  File "C:\Users\andre\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\MapsModelsImporter\google_maps.py", line 176, in filesToBlender
    drawcallId += 1
  File "C:\Users\andre\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\MapsModelsImporter\google_maps.py", line 60, in extractUniforms
    import bpy
KeyError: '$Globals'

location: <unknown location>:-1
```

 - GTX1080
 - 0.2.2
 - Version of RenderDoc 1.7
 - Version of Blender 2.82

**Comment by eliemichel** [comment]
No, it is not possible as is because the extraction code has been tailored for Google Maps (it doesn't even work on Google Earth for instance). Furthermore, **I don't intend to provide a tool for stealing artistic work**.

If the reason you want to extract models from a game is purely educational, I invite you to read [the blog post](https://blog.exppad.com/article/importing-actual-3d-models-from-google-maps) for which this MapsModelsImporter has initially been released. It goes far beyond Google Maps, but you'll have to roll up your sleeves. It'll be... educational. ^^

**Comment by AccountZeroName** [comment]
I started the game and made a capture(RenderDoc). I want to import the scene to another engine, not in order to steal, but just to see how this scene will look on another engine.
For example, like here:
https://youtu.be/yPLxCm3SyPU

**Comment by eliemichel** [comment]
I understand, it's fair, but anyway it is a lot of work to extend this add-on for this compared to the number of use case (it needs to be done for each game, or be done in a very generic way but it's harder). Again, you can follow the blog post to do this work yourself if you really need so.

Also note that getting the visual look of a model in another engine will require work anyway for adapting shaders and so on.
