### ISSUE TITLE
blender error 

### ISSUE THREAD

**Issue by serhaterman** [eliemichel/MapsModelsImporter#7]
i can't import to blender rdc file. it says "Could not find the beginning of the relevant 3D draw calls". any clue?

**Comment by alastaira** [comment]
Are you using Blender 2.8? On what OS?

**Comment by serhaterman** [comment]
yes, i'm using blender 2.8 on windows 10. i tried with renderdoc 1.4, 1.2 and 1.1.

**Comment by eliemichel** [comment]
Hi @serhaterman 
This messages is from here: https://github.com/eliemichel/MapsModelsImporter/blob/master/blender/MapsModelsImporter/google_maps_rd.py#L50
It means that the add-on could not recognize the part of the capture file that relates to the rendering of 3D meshes. It might be either:
 - That your GPU behaves slightly differently than the tested ones. There are already a couple of alternatives implemented, because some GPU/versions of chrome are a bit different, I could eventually add one for your's; or
 - You recorded a frame with no 3D information. This can be because you were not moving in the 3D view at the same time or because your browser turned 3D off. In the former case, try to capture again, potentially in burst with some delay. In the latter, your GPU might not be supported.
In either cases, please provide your .rdc file and the version of RenderDoc that has been used to capture it.
Thanks,
É.
