### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by tackattack** [eliemichel/MapsModelsImporter#86]
not an issue and I don't know if I should put this here, but is it possible to import rdc captures from other programs using this?

**Comment by eliemichel** [comment]
Hi @tackattack, this is a relevant place for questions as well.
It is not possible, and will not be except for other 3D maps providers because 1. it requires dedicated work for any source and also 2. I don't want this tool to be a way to steal artistic work. What you are looking for is a "3D mesh reaping tool".
